name: "Toucan"
description: "The Markdown-based static site generator written in Swift"
language: "en-US"
navigation:
    - label: "News"
      url: "/news/"
    - label: "Documentation"
      url: "/docs/"
    - label: "Templates"
      url: "/templates/"
    - label: "Showcases"
      url: "/showcases/"
    - label: "Community"
      url: "https://github.com/toucansites/toucan/discussions"
    - label: "Support"
      url: "/support/"
