baseUrl: "https://toucansites.com/"
locale: "en-US"
name: "Toucan"
description: "The Markdown-based static site generator written in Swift"
navigation:
    - label: "News"
      url: "/news/"
    - label: "Docs"
      url: "/docs/"
    - label: "FAQ"
      url: "/faq/"
    - label: "Showcases"
      url: "/showcases/"
    - label: "Contact"
      url: "/contact/"
