name: Build and Deploy with Toucan

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'

jobs:
  deploy-page:
    uses: BinaryBirds/github-workflows/.github/workflows/deploy.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write